### ISSUE TITLE
Cannot find name 'firebase'

### ISSUE THREAD

**Issue by gigocabrera** [SteveEmmerich/tutorials#1]
Hi,

I'm following your tutorial and cloned your repo on my local but I am getting the following error message when I try to run the app

> TypeScript error: C:/ionic/tutorials/i2fbp1/todoer/app/providers/data/data.ts(11,18): Error TS2304: Cannot find name 'firebase'

Can you help?

**Comment by SteveEmmerich** [comment]
That error is normal it should not stop anything from running. If it does please let me know.

**Comment by gigocabrera** [comment]
Steve, thank you for your quick reply. You were right, it did not stop the app from running. But I found a nice workaround to get rid of the error message, by adding the following right before the `@Injectable()` decorator

```
// Firebase
declare var firebase: any;
```

**Comment by anil826** [comment]
Same issue here .. any solution ??

```
TypeScript error: /Users/anilyadav/Desktop/ionic-conference-app/app/providers/data/data.ts(4,26): Error TS2307: Cannot find module 'firebase'.
TypeScript error: /Users/anilyadav/Desktop/ionic-conference-app/app/providers/data/data.ts(11,1): Error TS1206: Decorators are not valid here.
TypeScript error: /Users/anilyadav/Desktop/ionic-conference-app/app/providers/data/data.ts(27,12): Error TS2339: Property '_todos$' does not exist on type 'Data'.
TypeScript error: /Users/anilyadav/Desktop/ionic-conference-app/app/providers/data/data.ts(36,17): Error TS2339: Property '_todos$' does not exist on type 'Data'.
```
